version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=quizdb
      - POSTGRES_USER=tasriad
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'