version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=questiondb
      - POSTGRES_USER=tasriad
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'